"""Canonical RefraTranslator product naming."""

PRODUCT_NAME = "RefraTranslator"
PROJECT_SLUG = "refra-translator"
GUI_PROCESS_NAME = f"{PROJECT_SLUG}-gui"
LIVE_PROCESS_NAME = PROJECT_SLUG

API_KEY_ENV = "REFRA_TRANSLATOR_API_KEY"
LEGACY_API_KEY_ENV = "GAME_SCREEN_TRANSLATOR_API_KEY"
LIVE_TEST_ENV = "REFRA_TRANSLATOR_LIVE"
LEGACY_LIVE_TEST_ENV = "GAME_TRANSLATOR_LIVE"
